---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/react"
    schedule:
      interval: "weekly"
  - package-ecosystem: gradle
    directory: "/api"
    schedule:
      interval: "weekly"
