---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/react"
    schedule:
      interval: "weekly"
  - package-ecosystem: gradle
    directory: "/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10 
    allow:
      - dependency-type: "all"
