export const SHOW_LIST_ACTION = "SHOW_LIST_ACTION"
export const DECREASE_QUANTITY_ACTION = "DECREASE_QUANTITY_ACTION"
export const INCREASE_QUANTITY_ACTION = "INCREASE_QUANTITY_ACTION"
export const DELETE_ACTION = "DELETE_ACTION"